# Generated by Django 3.0.4 on 2020-03-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=64, null=True, verbose_name='Label')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Token')),
                ('expires', models.DateTimeField(verbose_name='Expiration Date')),
            ],
            options={
                'verbose_name': 'API Token',
                'verbose_name_plural': 'API Tokens',
            },
        ),
    ]
