# Generated by Django 3.0.4 on 2020-03-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200323_2138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={'verbose_name': 'توکن', 'verbose_name_plural': 'توکن\u200cها'},
        ),
        migrations.AlterField(
            model_name='token',
            name='expires',
            field=models.DateTimeField(verbose_name='تاریخ انقضا'),
        ),
        migrations.AlterField(
            model_name='token',
            name='label',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='برچسب'),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(blank=True, help_text='به صورت خودکار تکمیل خواهد شد.', max_length=64, null=True, unique=True, verbose_name='توکن'),
        ),
    ]
