# Generated by Django 3.0.4 on 2020-03-31 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_prediction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={},
        ),
    ]
