# Generated by Django 3.0.4 on 2020-03-31 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200331_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expires',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='token',
            name='label',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
