# Generated by Django 3.0.4 on 2020-03-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200331_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expires',
            field=models.DateTimeField(verbose_name='Expires at'),
        ),
        migrations.AlterField(
            model_name='token',
            name='label',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Token'),
        ),
    ]
