# Generated by Django 3.0.4 on 2020-03-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='Concept ID')),
                ('type', models.CharField(choices=[('disease', 'Disease'), ('symptom', 'Symptom')], max_length=16, verbose_name='Concept Type')),
            ],
            options={
                'verbose_name': 'Concept',
                'verbose_name_plural': 'Concepts',
            },
        ),
    ]
