# Generated by Django 3.0.4 on 2020-03-23 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predicting', '0002_translation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.TextField(verbose_name='Condition')),
                ('factor', models.FloatField(verbose_name='Factor')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predicting.Concept', verbose_name='Concept')),
            ],
            options={
                'verbose_name': 'Condition',
                'verbose_name_plural': 'Conditions',
            },
        ),
    ]
