# Generated by Django 3.0.4 on 2020-03-23 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predicting', '0003_condition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concept',
            options={'verbose_name': 'شناسه', 'verbose_name_plural': 'شناسه\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='condition',
            options={'verbose_name': 'شرط', 'verbose_name_plural': 'شرایط'},
        ),
        migrations.AlterModelOptions(
            name='translation',
            options={'verbose_name': 'ترجمه', 'verbose_name_plural': 'ترجمه\u200cها'},
        ),
        migrations.AlterField(
            model_name='concept',
            name='id',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='شناسه'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='type',
            field=models.CharField(choices=[('disease', 'بیماری'), ('symptom', 'علامت')], max_length=16, verbose_name='نوع شناسه'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predicting.Concept', verbose_name='شناسه'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='condition',
            field=models.TextField(verbose_name='شرط'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='factor',
            field=models.FloatField(verbose_name='ضریب'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predicting.Concept', verbose_name='شناسه'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='locale',
            field=models.CharField(choices=[('en-us', 'English (United States)'), ('fa-ir', 'فارسی (ایران)')], max_length=5, verbose_name='زبان'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='string',
            field=models.CharField(max_length=128, verbose_name='رشته'),
        ),
        migrations.CreateModel(
            name='DiseaseFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.PositiveIntegerField(verbose_name='فراوانی')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predicting.Concept', verbose_name='شناسه')),
            ],
            options={
                'verbose_name': 'فراوانی بیماری',
                'verbose_name_plural': 'فراوانی\u200cهای بیماری\u200cها',
            },
        ),
    ]
