# Generated by Django 3.0.4 on 2020-03-24 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predicting', '0004_auto_20200323_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='concept',
            field=models.ForeignKey(limit_choices_to=models.Q(type='disease'), on_delete=django.db.models.deletion.CASCADE, to='predicting.Concept', verbose_name='شناسه'),
        ),
        migrations.AlterField(
            model_name='diseasefrequency',
            name='concept',
            field=models.ForeignKey(limit_choices_to=models.Q(type='disease'), on_delete=django.db.models.deletion.CASCADE, to='predicting.Concept', verbose_name='شناسه'),
        ),
        migrations.CreateModel(
            name='Pairing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.ForeignKey(limit_choices_to=models.Q(type='disease'), on_delete=django.db.models.deletion.CASCADE, related_name='disease', to='predicting.Concept', verbose_name='شناسه بیماری')),
                ('symptom', models.ForeignKey(limit_choices_to=models.Q(type='symptom'), on_delete=django.db.models.deletion.CASCADE, related_name='symptom', to='predicting.Concept', verbose_name='شناسه علامت')),
            ],
            options={
                'verbose_name': 'علامت بیماری',
                'verbose_name_plural': 'علائم بیماری\u200cها',
            },
        ),
    ]
