# Generated by Django 3.0.4 on 2020-03-24 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predicting', '0006_auto_20200324_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='diseasefrequency',
            name='concept',
        ),
        migrations.RemoveField(
            model_name='pairing',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='pairing',
            name='symptom',
        ),
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='translation',
            name='concept',
        ),
        migrations.AlterModelOptions(
            name='concept',
            options={},
        ),
        migrations.RemoveField(
            model_name='concept',
            name='type',
        ),
        migrations.AlterField(
            model_name='concept',
            name='id',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Condition',
        ),
        migrations.DeleteModel(
            name='DiseaseFrequency',
        ),
        migrations.DeleteModel(
            name='Pairing',
        ),
        migrations.DeleteModel(
            name='Translation',
        ),
        migrations.AddField(
            model_name='symptom',
            name='concept',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='predicting.Concept'),
        ),
        migrations.AddField(
            model_name='disease',
            name='concept',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='predicting.Concept'),
        ),
    ]
