# Generated by Django 3.0.4 on 2020-03-24 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predicting', '0007_auto_20200324_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='concept',
        ),
        migrations.RemoveField(
            model_name='symptom',
            name='concept',
        ),
        migrations.DeleteModel(
            name='Concept',
        ),
        migrations.DeleteModel(
            name='Disease',
        ),
        migrations.DeleteModel(
            name='Symptom',
        ),
    ]
