# Generated by Django 3.0.4 on 2020-03-24 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predicting', '0009_concept_condition_diseasefrequency_translation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='diseasefrequency',
            name='concept',
        ),
        migrations.AlterModelOptions(
            name='concept',
            options={},
        ),
        migrations.AlterModelOptions(
            name='translation',
            options={},
        ),
        migrations.RemoveField(
            model_name='concept',
            name='type',
        ),
        migrations.AlterField(
            model_name='concept',
            name='id',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='translation',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predicting.Concept'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='locale',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='translation',
            name='string',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Condition',
        ),
        migrations.DeleteModel(
            name='DiseaseFrequency',
        ),
        migrations.AddField(
            model_name='symptom',
            name='concept',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='predicting.Concept'),
        ),
        migrations.AddField(
            model_name='disease',
            name='concept',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='predicting.Concept'),
        ),
    ]
