# Generated by Django 3.0.4 on 2020-03-24 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predicting', '0010_auto_20200324_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptom',
            name='concept',
        ),
        migrations.DeleteModel(
            name='Disease',
        ),
        migrations.DeleteModel(
            name='Symptom',
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('predicting.concept',),
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('predicting.concept',),
        ),
    ]
