# Generated by Django 3.0.4 on 2020-03-24 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predicting', '0011_auto_20200324_2100'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Disease',
        ),
        migrations.DeleteModel(
            name='Symptom',
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='predicting.Concept')),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='predicting.Concept')),
            ],
        ),
    ]
