# Generated by Django 3.0.4 on 2020-03-24 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predicting', '0012_auto_20200324_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='concept',
        ),
        migrations.RemoveField(
            model_name='symptom',
            name='concept',
        ),
        migrations.AlterField(
            model_name='disease',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='predicting.Concept'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='predicting.Concept'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='concept',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='predicting.Concept'),
        ),
    ]
