# Generated by Django 3.0.4 on 2020-03-24 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predicting', '0014_disease_x'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predicting.Concept'),
        ),
    ]
