# Generated by Django 3.0.4 on 2020-03-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicting', '0015_auto_20200324_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='string',
            field=models.CharField(max_length=256),
        ),
    ]
