# Generated by Django 3.0.4 on 2020-03-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicting', '0017_auto_20200324_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='locale',
            field=models.CharField(choices=[('en-us', 'English (United States)'), ('fa-ir', 'فارسی (ایران)')], max_length=5),
        ),
        migrations.AlterField(
            model_name='translation',
            name='string',
            field=models.CharField(max_length=256),
        ),
    ]
