# Generated by Django 3.0.4 on 2020-03-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicting', '0018_auto_20200324_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=256, verbose_name='برچسب')),
                ('condition', models.TextField(help_text='این عبارت می\u200cبایست یک Expression معتبر پایتونی باشد.', verbose_name='شرط')),
            ],
            options={
                'verbose_name': 'شرایط',
                'verbose_name_plural': 'شرایط',
            },
        ),
        migrations.AlterModelOptions(
            name='concept',
            options={'verbose_name': 'مفهوم', 'verbose_name_plural': 'مفاهیم'},
        ),
        migrations.AlterModelOptions(
            name='disease',
            options={'verbose_name': 'بیماری', 'verbose_name_plural': 'بیماری\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='symptom',
            options={'verbose_name': 'علامت', 'verbose_name_plural': 'علائم'},
        ),
        migrations.AlterModelOptions(
            name='translation',
            options={'verbose_name': 'ترجمه', 'verbose_name_plural': 'ترجمه\u200cها'},
        ),
        migrations.RemoveField(
            model_name='disease',
            name='x',
        ),
        migrations.AlterField(
            model_name='concept',
            name='id',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='شناسه'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='locale',
            field=models.CharField(choices=[('en-us', 'English (United States)'), ('fa-ir', 'فارسی (ایران)')], max_length=5, verbose_name='زبان'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='string',
            field=models.CharField(max_length=256, verbose_name='رشته'),
        ),
    ]
