# Generated by Django 3.0.4 on 2020-03-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicting', '0019_auto_20200324_2122'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Condition',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='id',
        ),
        migrations.RemoveField(
            model_name='symptom',
            name='id',
        ),
        migrations.AlterField(
            model_name='translation',
            name='concept',
            field=models.CharField(max_length=16),
        ),
        migrations.DeleteModel(
            name='Concept',
        ),
        migrations.DeleteModel(
            name='Disease',
        ),
        migrations.DeleteModel(
            name='Symptom',
        ),
    ]
