# Generated by Django 3.0.4 on 2020-03-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicting', '0020_auto_20200324_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('concept', models.CharField(max_length=16, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('concept', models.CharField(max_length=16, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
