# Generated by Django 3.0.4 on 2020-03-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicting', '0021_disease_symptom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=256, verbose_name='برچسب')),
                ('expression', models.TextField(help_text='متن وارد\u200cشده می\u200cبایست یک Expression معتبر پایتونی باشد.', verbose_name='عبارت')),
            ],
        ),
        migrations.AlterModelOptions(
            name='disease',
            options={'verbose_name': 'بیماری', 'verbose_name_plural': 'بیماری\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='symptom',
            options={'verbose_name': 'علامت', 'verbose_name_plural': 'علائم'},
        ),
        migrations.AlterField(
            model_name='disease',
            name='concept',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='شناسه'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='concept',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='شناسه'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='concept',
            field=models.CharField(max_length=16, verbose_name='شناسه'),
        ),
    ]
