# Generated by Django 3.0.4 on 2020-03-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicting', '0023_diseasecondition'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasecondition',
            name='factor',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
