# Generated by Django 3.0.4 on 2020-03-24 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predicting', '0024_diseasecondition_factor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condition',
            options={'verbose_name': 'شرایط', 'verbose_name_plural': 'شرایط'},
        ),
        migrations.AlterModelOptions(
            name='diseasecondition',
            options={'verbose_name': 'شرایط بیماری', 'verbose_name_plural': 'شرایط بیماری\u200cها'},
        ),
        migrations.AlterField(
            model_name='diseasecondition',
            name='conditions',
            field=models.ManyToManyField(to='predicting.Condition', verbose_name='شرایط لازمه'),
        ),
        migrations.AlterField(
            model_name='diseasecondition',
            name='factor',
            field=models.FloatField(verbose_name='ضریب تاثیر'),
        ),
        migrations.CreateModel(
            name='DiseaseSymptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predicting.Disease')),
                ('symptoms', models.ManyToManyField(to='predicting.Symptom')),
            ],
        ),
    ]
