# Generated by Django 3.0.4 on 2020-03-24 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predicting', '0025_auto_20200324_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasesymptom',
            name='disease',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='predicting.Disease'),
        ),
    ]
