# Generated by Django 3.0.4 on 2020-03-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicting', '0027_auto_20200324_2200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diseasename',
            options={'verbose_name': 'عنوان', 'verbose_name_plural': 'عناوین'},
        ),
        migrations.AlterModelOptions(
            name='symptomname',
            options={'verbose_name': 'عنوان', 'verbose_name_plural': 'عناوین'},
        ),
        migrations.AlterField(
            model_name='diseasename',
            name='locale',
            field=models.CharField(choices=[('en', 'English (United States)'), ('fa', 'فارسی (ایران)')], max_length=5, verbose_name='زبان'),
        ),
        migrations.AlterField(
            model_name='symptomname',
            name='locale',
            field=models.CharField(choices=[('en', 'English (United States)'), ('fa', 'فارسی (ایران)')], max_length=5, verbose_name='زبان'),
        ),
    ]
