# Generated by Django 3.0.4 on 2020-03-30 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predicting', '0031_association_concept_condition_disease_information_primitivecondition_symptom_translation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concept',
            options={'verbose_name': 'Concept'},
        ),
    ]
