# Generated by Django 3.0.4 on 2020-03-30 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predicting', '0033_auto_20200330_1909'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='information',
            unique_together={('concept', 'language')},
        ),
    ]
