# Generated by Django 3.0.4 on 2020-03-31 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predicting', '0036_auto_20200331_1024'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='association',
            unique_together={('disease', 'symptom')},
        ),
    ]
