# Generated by Django 3.0.4 on 2020-03-31 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predicting', '0037_auto_20200331_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concept',
            options={},
        ),
        migrations.RenameField(
            model_name='primitivecondition',
            old_name='condition',
            new_name='expression',
        ),
    ]
