# Generated by Django 3.0.4 on 2020-03-31 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predicting', '0040_symptom_values'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='association',
            options={'verbose_name': 'Association', 'verbose_name_plural': 'Associations'},
        ),
        migrations.AlterModelOptions(
            name='concept',
            options={'verbose_name': 'Concept', 'verbose_name_plural': 'Concepts'},
        ),
        migrations.AlterModelOptions(
            name='condition',
            options={'verbose_name': 'Condition', 'verbose_name_plural': 'Conditions'},
        ),
        migrations.AlterModelOptions(
            name='disease',
            options={'verbose_name': 'Disease', 'verbose_name_plural': 'Diseases'},
        ),
        migrations.AlterModelOptions(
            name='information',
            options={'verbose_name': 'Information', 'verbose_name_plural': 'Information'},
        ),
        migrations.AlterModelOptions(
            name='primitivecondition',
            options={'verbose_name': 'Primitive Condition', 'verbose_name_plural': 'Primitive Conditions'},
        ),
        migrations.AlterModelOptions(
            name='symptom',
            options={'verbose_name': 'Symptom', 'verbose_name_plural': 'Symptoms'},
        ),
        migrations.AlterModelOptions(
            name='translation',
            options={'verbose_name': 'Translation', 'verbose_name_plural': 'Translations'},
        ),
        migrations.AlterField(
            model_name='association',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predicting.Disease', verbose_name='Disease'),
        ),
        migrations.AlterField(
            model_name='association',
            name='symptom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predicting.Symptom', verbose_name='Symptom'),
        ),
        migrations.AlterField(
            model_name='association',
            name='weight',
            field=models.IntegerField(default=1, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='id',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predicting.Disease', verbose_name='Disease'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='factor',
            field=models.FloatField(verbose_name='Factor'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='required_conditions',
            field=models.ManyToManyField(related_name='required_condition', to='predicting.PrimitiveCondition', verbose_name='Required Conditions'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='concept',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='predicting.Concept', verbose_name='Concept'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='red_flag',
            field=models.BooleanField(default=False, verbose_name='Red Flag'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='triage',
            field=models.CharField(blank=True, choices=[('low', 'کم\u200cخطر'), ('medium', 'متوسط'), ('high', 'پر\u200cخطر')], max_length=6, null=True, verbose_name='Triage'),
        ),
        migrations.AlterField(
            model_name='information',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predicting.Concept', verbose_name='Concept'),
        ),
        migrations.AlterField(
            model_name='information',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fa', 'فارسی')], max_length=2, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='information',
            name='string',
            field=models.TextField(verbose_name='String'),
        ),
        migrations.AlterField(
            model_name='primitivecondition',
            name='expression',
            field=models.TextField(verbose_name='Expression'),
        ),
        migrations.AlterField(
            model_name='primitivecondition',
            name='label',
            field=models.CharField(max_length=256, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='concept',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='predicting.Concept', verbose_name='Concept'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='values',
            field=models.CharField(choices=[('[-1, 1]', '[-1, 1]'), ('[0, 1]', '[0, 1]'), ('-1, 0, 1', '-1, 0, 1')], max_length=16, verbose_name='Values'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predicting.Concept', verbose_name='Concept'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fa', 'فارسی')], max_length=2, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='string',
            field=models.TextField(verbose_name='String'),
        ),
    ]
