# Generated by Django 3.0.4 on 2020-04-06 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predicting', '0043_auto_20200406_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('label', models.CharField(help_text='Shown in admin only.', max_length=128, verbose_name='Label')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.RemoveField(
            model_name='information',
            name='string',
        ),
        migrations.AlterField(
            model_name='diseasetype',
            name='label',
            field=models.CharField(help_text='Only shown in admin.', max_length=256, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='diseasetype',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='InformationProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predicting.Information')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predicting.Property')),
            ],
            options={
                'verbose_name': 'Information Property',
                'verbose_name_plural': 'Information Properties',
            },
        ),
    ]
