# Generated by Django 3.0.4 on 2020-04-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicting', '0044_auto_20200406_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='weight',
            field=models.FloatField(default=1, verbose_name='Weight'),
        ),
    ]
